create table if not exists public.daily_reports (
  report_date date primary key,
  markdown text,
  html text,
  report_url text,
  markdown_url text,
  topic_heat jsonb not null default '[]'::jsonb,
  consensus jsonb not null default '{}'::jsonb,
  risk jsonb not null default '{}'::jsonb,
  blogger_stats jsonb not null default '[]'::jsonb,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.report_runs (
  id bigint generated by default as identity primary key,
  report_date date not null,
  status text not null,
  message text,
  report_url text,
  created_at timestamptz not null default now()
);

create index if not exists report_runs_report_date_idx
  on public.report_runs (report_date desc, created_at desc);

alter table public.daily_reports enable row level security;
alter table public.report_runs enable row level security;

drop policy if exists "daily reports are readable" on public.daily_reports;
create policy "daily reports are readable"
  on public.daily_reports
  for select
  using (true);

drop policy if exists "report runs are service-role only" on public.report_runs;

-- Writes should use SUPABASE_SERVICE_ROLE_KEY from GitHub Actions.
